---
  title: "Task Manager"
  package: "tasks"
  summary: "Manage your projects & tasks with ease."
  description: "Manage your projects & tasks with ease."
  version: "1.0.0"
  developer: "Tommy Labs GmbH"
  homepage: "https://mytommy.com"
  private: false
  locales:
    - en-US
    - zh-CN
  permissions:
    # task_list_filters:
    #   title: "Filter Tasks"
    #   hint: "Select which tasks will appear in this list"
    #   resource_type: "Fragment"
    #   resource_kind: "TaskList"
    #   operations:
    #     - read
    task_list_read_access:
      title: "Who Can See List"
      hint: "Select who can view this list"
      resource_type: "Fragment"
      resource_kind: "TaskList"
      private: true
      roles:
        - Team Manager
        - Team Admin
      operations:
        - read
    task_list_edit_access:
      title: "Who Can Edit List"
      hint: "Select who can edit this list"
      resource_type: "Fragment"
      resource_kind: "TaskList"
      private: true
      roles:
        - Team Manager
        - Team Admin
      operations:
        - edit
    task_create_access:
      title: "Who Can Create Tasks"
      hint: "Select who can create tasks"
      resource_type: "Fragment"
      resource_kind: "Task"
      private: true
      roles:
        - Team Manager
        - Team Admin
      operations:
        - create
    task_edit_access:
      title: "Who Can Edit Tasks"
      hint: "Select who can edit tasks"
      resource_type: "Fragment"
      resource_kind: "Task"
      private: true
      roles:
        - Team Manager
        - Team Admin
      operations:
        - edit
  views:
    index:
      title: "Tasks"
      file: "views/index.html"
      type: "page"
      index: true
      framed: false
      assets:
        -
          type: "stylesheet"
          file: "views/build/bundle.css"
        -
          type: "javascript"
          file: "views/build/bundle.js"
        -
          type: "template"
          file: "views/build/bundle.tpl.html"
