---
  title: "Task Manager"
  package: "tasks"
  summary: "Manage your projects & tasks with ease."
  description: "Manage your projects & tasks with ease."
  version: "1.0.0"
  developer: "Tommy Labs GmbH"
  homepage: "https://mytommy.com"
  private: false
  languages:
   - en-US
   - zh-CN
  # roles:
  #   - Team Member
  #   - Team Manager
  views:
    index:
      title: "Tasks"
      file: "views/index.html"
      type: "page"
      index: true
      framed: false
      # roles:
      #   - Team Member
      #   - Team Manager
      assets:
        -
          type: "stylesheet"
          file: "views/build/bundle.css"
        -
          type: "javascript"
          file: "views/build/bundle.js"
        -
          type: "template"
          file: "views/build/bundle.tpl.html"
